sudo: required
services: docker

before install:
  - docker build -t cockochan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cockochan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-420325709910"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
